name: Continuous Integration
on:
  push:
    branches:
      - main
      - 'EXP-**'
jobs:
  call-continuous-integration-reusable:
    uses: Nageshadevops/github-reusable-workflows/.github/workflows/ci.yml@main
    with:
      project_name: expense-frontend
      npm_install: false
      release_archive_file: "*"
    secrets: inherit